[target.riscv32imc-unknown-none-elf]
rustflags = ["-C", "link-arg=-Tmemory.x", "-C", "link-arg=-Tlink.x"]

runner = ".cargo/runner.sh"

[build]
target-dir = "../target/suite"
target = "riscv32imc-unknown-none-elf"

[alias]
run-qemu = "run --no-default-features --features platform_qemu_virt -- -q"
run-qemu-opt = "run --no-default-features --features platform_qemu_virt --release -- -q"
test-qemu = "test --no-default-features --features platform_qemu_virt -- -q"
test-qemu-opt = "test --no-default-features --features platform_qemu_virt --release -- -q"
run-verilator = "run --no-default-features --features platform_verilator_earlgrey -- -v"
run-verilator-opt = "run --no-default-features --features platform_verilator_earlgrey --release -- -v"
test-verilator = "test --no-default-features --features platform_verilator_earlgrey -- -v"
test-verilator-opt = "test --no-default-features --features platform_verilator_earlgrey --release -- -v"
build-nexysvideo = "build --no-default-features --features platform_nexysvideo_earlgrey"
build-nexysvideo-opt = "build --no-default-features --features platform_nexysvideo_earlgrey --release"
build-nexysvideo-test = "test --no-default-features --features platform_nexysvideo_earlgrey --no-run"
