[target.riscv32imc-unknown-none-elf]
rustflags = [
  "-C", "link-arg=-Tmemory.x",
  "-C", "link-arg=-Tlink.x",
]

runner = ".cargo/runner.sh"

[build]
target = "riscv32imc-unknown-none-elf"

[alias]
run-qemu = "run --no-default-features --features platform_qemu_virt -- -q"
test-qemu = "test --no-default-features --features platform_qemu_virt -- -q"
run-verilator = "run --no-default-features --features platform_verilator_earlgrey -- -v"
test-verilator = "test --no-default-features --features platform_verilator_earlgrey -- -v"
